### ISSUE TITLE
word2vec

### ISSUE THREAD

**Issue by graphific** [davisliang/automatedMTL#10]
Would love to try the project: I get apache storm to collect tweets and write the cleaned text and hashtag away to `tweetnet/data/dump.txt`

But what then? Starting with `utils/embeddingGeneration.py`:
Where does the word2vec vocab in `tweetnet/data/vocabs.txt` come from, as it's missing?

That and the `word2vec_dict.pkl`

**Comment by davisliang** [comment]
The data should be sourced from here:
http://mccormickml.com/2016/04/12/googles-pretrained-word2vec-model-in-python/

vocabs.txt should be the text lexicon constructed from this data and word2vec_dict.pkl is a dictionary from string to semantic w2v vectors in pickled form. 

@syan3737 @anapetrova you can follow up with further details.

@graphific Some clarification: this code is in two parts; the part you're looking at now consists of older code that makes up the infinite data pipeline; which is useful for injecting the twitter data directly into a Tensorflow graph. All the model-based (everything not related to data preparation) code used in the actual research paper (multi-condition learning as implicit regularization) is in the "auto" directory.

**Comment by davisliang** [comment]
Notice: this issue has been closed because it has been inactive for over 14 days. You may reopen this issue if it has been closed in error.
